
/* This is generated by the genStubs.tcl tool (see the tcl distribution)
   out of the tdom.decls file */


/* !BEGIN!: Do not edit below this line. */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Exported function declarations:
 */

/* 0 */
EXTERN int		TclExpatObjCmd(ClientData dummy, Tcl_Interp *interp,
				int objc, Tcl_Obj *const objv[]);
/* 1 */
EXTERN int		CheckExpatParserObj(Tcl_Interp *interp,
				Tcl_Obj *const nameObj);
/* 2 */
EXTERN int		CHandlerSetInstall(Tcl_Interp *interp,
				Tcl_Obj *const expatObj,
				CHandlerSet *handlerSet);
/* 3 */
EXTERN int		CHandlerSetRemove(Tcl_Interp *interp,
				Tcl_Obj *const expatObj,
				char *handlerSetName);
/* 4 */
EXTERN CHandlerSet *	CHandlerSetCreate(const char *name);
/* 5 */
EXTERN CHandlerSet *	CHandlerSetGet(Tcl_Interp *interp,
				Tcl_Obj *const expatObj,
				char *handlerSetName);
/* 6 */
EXTERN void *		CHandlerSetGetUserData(Tcl_Interp *interp,
				Tcl_Obj *const expatObj,
				char *handlerSetName);
/* 7 */
EXTERN TclGenExpatInfo * GetExpatInfo(Tcl_Interp *interp,
				Tcl_Obj *const expatObj);
/* 8 */
EXTERN XML_Size		XML_GetCurrentLineNumber(XML_Parser parser);
/* 9 */
EXTERN XML_Size		XML_GetCurrentColumnNumber(XML_Parser parser);
/* 10 */
EXTERN XML_Index	XML_GetCurrentByteIndex(XML_Parser parser);
/* 11 */
EXTERN int		XML_GetCurrentByteCount(XML_Parser parser);
/* 12 */
EXTERN enum XML_Status	XML_SetBase(XML_Parser parser, const XML_Char *base);
/* 13 */
EXTERN const XML_Char *	 XML_GetBase(XML_Parser parser);
/* 14 */
EXTERN int		XML_GetSpecifiedAttributeCount(XML_Parser parser);
/* 15 */
EXTERN int		XML_GetIdAttributeIndex(XML_Parser parser);
/* 16 */
EXTERN domNode *	tcldom_getNodeFromName(Tcl_Interp *interp,
				char *nodeName, char **errMsg);
/* 17 */
EXTERN domDocument *	tcldom_getDocumentFromName(Tcl_Interp *interp,
				char *docName, char **errMsg);
/* 18 */
EXTERN SchemaData *	tdomGetSchemadata(void);
/* 19 */
EXTERN void		tcldom_createNodeObj(Tcl_Interp *interp,
				domNode *node, char *objCmdName);
/* 20 */
EXTERN domNode *	domCloneNode(domNode *node, int deep);
/* 21 */
EXTERN domDocument *	domCreateDoc(const char *baseURI,
				int storeLineColumn);
/* 22 */
EXTERN domDocument *	domCreateDocument(const char *uri,
				char *documentElementTagName);
/* 23 */
EXTERN void		domSetDocumentElement(domDocument *doc);
/* 24 */
EXTERN void		domFreeDocument(domDocument *doc,
				domFreeCallback freeCB, void *clientData);
/* 25 */
EXTERN domNode *	domNewElementNode(domDocument *doc,
				const char *tagName);
/* 26 */
EXTERN domTextNode *	domAppendNewTextNode(domNode *parent, char *value,
				domLength length, domNodeType nodeType,
				int disableOutputEscaping);
/* 27 */
EXTERN domException	domAppendChild(domNode *node, domNode *childToAppend);
/* 28 */
EXTERN domAttrNode *	domSetAttributeEx(domNode *node,
				const char *attributeName,
				domLength nameLength,
				const char *attributeValue,
				domLength valueLength);

typedef struct TdomStubs {
    int magic;
    void *hooks;

    int (*tclExpatObjCmd) (ClientData dummy, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]); /* 0 */
    int (*checkExpatParserObj) (Tcl_Interp *interp, Tcl_Obj *const nameObj); /* 1 */
    int (*cHandlerSetInstall) (Tcl_Interp *interp, Tcl_Obj *const expatObj, CHandlerSet *handlerSet); /* 2 */
    int (*cHandlerSetRemove) (Tcl_Interp *interp, Tcl_Obj *const expatObj, char *handlerSetName); /* 3 */
    CHandlerSet * (*cHandlerSetCreate) (const char *name); /* 4 */
    CHandlerSet * (*cHandlerSetGet) (Tcl_Interp *interp, Tcl_Obj *const expatObj, char *handlerSetName); /* 5 */
    void * (*cHandlerSetGetUserData) (Tcl_Interp *interp, Tcl_Obj *const expatObj, char *handlerSetName); /* 6 */
    TclGenExpatInfo * (*getExpatInfo) (Tcl_Interp *interp, Tcl_Obj *const expatObj); /* 7 */
    XML_Size (*xML_GetCurrentLineNumber) (XML_Parser parser); /* 8 */
    XML_Size (*xML_GetCurrentColumnNumber) (XML_Parser parser); /* 9 */
    XML_Index (*xML_GetCurrentByteIndex) (XML_Parser parser); /* 10 */
    int (*xML_GetCurrentByteCount) (XML_Parser parser); /* 11 */
    enum XML_Status (*xML_SetBase) (XML_Parser parser, const XML_Char *base); /* 12 */
    const XML_Char * (*xML_GetBase) (XML_Parser parser); /* 13 */
    int (*xML_GetSpecifiedAttributeCount) (XML_Parser parser); /* 14 */
    int (*xML_GetIdAttributeIndex) (XML_Parser parser); /* 15 */
    domNode * (*tcldom_getNodeFromName) (Tcl_Interp *interp, char *nodeName, char **errMsg); /* 16 */
    domDocument * (*tcldom_getDocumentFromName) (Tcl_Interp *interp, char *docName, char **errMsg); /* 17 */
    SchemaData * (*tdomGetSchemadata) (void); /* 18 */
    void (*tcldom_createNodeObj) (Tcl_Interp *interp, domNode *node, char *objCmdName); /* 19 */
    domNode * (*domCloneNode) (domNode *node, int deep); /* 20 */
    domDocument * (*domCreateDoc) (const char *baseURI, int storeLineColumn); /* 21 */
    domDocument * (*domCreateDocument) (const char *uri, char *documentElementTagName); /* 22 */
    void (*domSetDocumentElement) (domDocument *doc); /* 23 */
    void (*domFreeDocument) (domDocument *doc, domFreeCallback freeCB, void *clientData); /* 24 */
    domNode * (*domNewElementNode) (domDocument *doc, const char *tagName); /* 25 */
    domTextNode * (*domAppendNewTextNode) (domNode *parent, char *value, domLength length, domNodeType nodeType, int disableOutputEscaping); /* 26 */
    domException (*domAppendChild) (domNode *node, domNode *childToAppend); /* 27 */
    domAttrNode * (*domSetAttributeEx) (domNode *node, const char *attributeName, domLength nameLength, const char *attributeValue, domLength valueLength); /* 28 */
} TdomStubs;

extern const TdomStubs *tdomStubsPtr;

#ifdef __cplusplus
}
#endif

#if defined(USE_TDOM_STUBS)

/*
 * Inline function declarations:
 */

#define TclExpatObjCmd \
	(tdomStubsPtr->tclExpatObjCmd) /* 0 */
#define CheckExpatParserObj \
	(tdomStubsPtr->checkExpatParserObj) /* 1 */
#define CHandlerSetInstall \
	(tdomStubsPtr->cHandlerSetInstall) /* 2 */
#define CHandlerSetRemove \
	(tdomStubsPtr->cHandlerSetRemove) /* 3 */
#define CHandlerSetCreate \
	(tdomStubsPtr->cHandlerSetCreate) /* 4 */
#define CHandlerSetGet \
	(tdomStubsPtr->cHandlerSetGet) /* 5 */
#define CHandlerSetGetUserData \
	(tdomStubsPtr->cHandlerSetGetUserData) /* 6 */
#define GetExpatInfo \
	(tdomStubsPtr->getExpatInfo) /* 7 */
#define XML_GetCurrentLineNumber \
	(tdomStubsPtr->xML_GetCurrentLineNumber) /* 8 */
#define XML_GetCurrentColumnNumber \
	(tdomStubsPtr->xML_GetCurrentColumnNumber) /* 9 */
#define XML_GetCurrentByteIndex \
	(tdomStubsPtr->xML_GetCurrentByteIndex) /* 10 */
#define XML_GetCurrentByteCount \
	(tdomStubsPtr->xML_GetCurrentByteCount) /* 11 */
#define XML_SetBase \
	(tdomStubsPtr->xML_SetBase) /* 12 */
#define XML_GetBase \
	(tdomStubsPtr->xML_GetBase) /* 13 */
#define XML_GetSpecifiedAttributeCount \
	(tdomStubsPtr->xML_GetSpecifiedAttributeCount) /* 14 */
#define XML_GetIdAttributeIndex \
	(tdomStubsPtr->xML_GetIdAttributeIndex) /* 15 */
#define tcldom_getNodeFromName \
	(tdomStubsPtr->tcldom_getNodeFromName) /* 16 */
#define tcldom_getDocumentFromName \
	(tdomStubsPtr->tcldom_getDocumentFromName) /* 17 */
#define tdomGetSchemadata \
	(tdomStubsPtr->tdomGetSchemadata) /* 18 */
#define tcldom_createNodeObj \
	(tdomStubsPtr->tcldom_createNodeObj) /* 19 */
#define domCloneNode \
	(tdomStubsPtr->domCloneNode) /* 20 */
#define domCreateDoc \
	(tdomStubsPtr->domCreateDoc) /* 21 */
#define domCreateDocument \
	(tdomStubsPtr->domCreateDocument) /* 22 */
#define domSetDocumentElement \
	(tdomStubsPtr->domSetDocumentElement) /* 23 */
#define domFreeDocument \
	(tdomStubsPtr->domFreeDocument) /* 24 */
#define domNewElementNode \
	(tdomStubsPtr->domNewElementNode) /* 25 */
#define domAppendNewTextNode \
	(tdomStubsPtr->domAppendNewTextNode) /* 26 */
#define domAppendChild \
	(tdomStubsPtr->domAppendChild) /* 27 */
#define domSetAttributeEx \
	(tdomStubsPtr->domSetAttributeEx) /* 28 */

#endif /* defined(USE_TDOM_STUBS) */

/* !END!: Do not edit above this line. */
